/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Entitlement = { 'pro' : null } |
  { 'free' : null };
export interface TemplateMetadata {
  'id' : string,
  'modifiedAt' : Time,
  'name' : string,
  'createdAt' : Time,
  'description' : string,
  'templateType' : TemplateType,
  'entitlement' : Entitlement,
}
export type TemplateType = { 'video' : null } |
  { 'photo' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string, 'entitlement' : Entitlement }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteTemplate' : ActorMethod<[string], undefined>,
  'getAllTemplates' : ActorMethod<[], Array<TemplateMetadata>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getTemplate' : ActorMethod<[string], [] | [TemplateMetadata]>,
  'getTemplatesByEntitlement' : ActorMethod<
    [Entitlement],
    Array<TemplateMetadata>
  >,
  'getTemplatesByType' : ActorMethod<[TemplateType], Array<TemplateMetadata>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveTemplate' : ActorMethod<[TemplateMetadata], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];