/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const TemplateType = IDL.Variant({
  'video' : IDL.Null,
  'photo' : IDL.Null,
});
export const Entitlement = IDL.Variant({ 'pro' : IDL.Null, 'free' : IDL.Null });
export const TemplateMetadata = IDL.Record({
  'id' : IDL.Text,
  'modifiedAt' : Time,
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'templateType' : TemplateType,
  'entitlement' : Entitlement,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'entitlement' : Entitlement,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteTemplate' : IDL.Func([IDL.Text], [], []),
  'getAllTemplates' : IDL.Func([], [IDL.Vec(TemplateMetadata)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getTemplate' : IDL.Func([IDL.Text], [IDL.Opt(TemplateMetadata)], ['query']),
  'getTemplatesByEntitlement' : IDL.Func(
      [Entitlement],
      [IDL.Vec(TemplateMetadata)],
      ['query'],
    ),
  'getTemplatesByType' : IDL.Func(
      [TemplateType],
      [IDL.Vec(TemplateMetadata)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveTemplate' : IDL.Func([TemplateMetadata], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const TemplateType = IDL.Variant({ 'video' : IDL.Null, 'photo' : IDL.Null });
  const Entitlement = IDL.Variant({ 'pro' : IDL.Null, 'free' : IDL.Null });
  const TemplateMetadata = IDL.Record({
    'id' : IDL.Text,
    'modifiedAt' : Time,
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'templateType' : TemplateType,
    'entitlement' : Entitlement,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'entitlement' : Entitlement,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteTemplate' : IDL.Func([IDL.Text], [], []),
    'getAllTemplates' : IDL.Func([], [IDL.Vec(TemplateMetadata)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getTemplate' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(TemplateMetadata)],
        ['query'],
      ),
    'getTemplatesByEntitlement' : IDL.Func(
        [Entitlement],
        [IDL.Vec(TemplateMetadata)],
        ['query'],
      ),
    'getTemplatesByType' : IDL.Func(
        [TemplateType],
        [IDL.Vec(TemplateMetadata)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveTemplate' : IDL.Func([TemplateMetadata], [], []),
  });
};

export const init = ({ IDL }) => { return []; };